-- =====================================================================
-- WineSelection — Schema DDL (schema `wineselection`)
-- Mesmo projeto Supabase do FestasBV/Goals (diogoandrefsilva-personalapps-database),
-- schema isolado — não mexe em nada dos outros.
-- Correr no SQL Editor do Supabase, por esta ordem: schema.sql -> functions.sql
-- -> policies.sql -> admin_pass_temp.sql. Ver db/README.md para os passos
-- manuais (expor o schema na API, redirect URLs).
--
-- NOTA sobre IDs: cada mutação é um POST/PATCH/DELETE de uma linha de cada
-- vez — por isso os `id` são `GENERATED BY DEFAULT AS IDENTITY` (mesma
-- convenção do Goals/FestasBV): a app lê o id de volta da resposta do POST
-- (`Prefer: return=representation`), nunca o inventa.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS wineselection;

-- A `service_role` (a Edge Function `sugerir-vinho`) NÃO tem acesso a schemas
-- fora de `public` só por ser service_role — RLS bypass (BYPASSRLS) é só
-- sobre policies, não sobre GRANTs. Sem isto, qualquer pedido feito com a
-- service_role key contra `wineselection.*` falha com "permission denied for
-- schema wineselection" (42501), silenciosamente do lado de quem chama.
GRANT USAGE ON SCHEMA wineselection TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wineselection TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA wineselection TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA wineselection GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA wineselection GRANT USAGE, SELECT ON SEQUENCES TO service_role;

-- ---------------------------------------------------------------------
-- Controlo de acesso (mesmo padrão do Goals/FestasBV)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS wineselection.allowed_users (
  email      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT allowed_users_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS wineselection.access_requests (
  email        text NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT access_requests_pkey PRIMARY KEY (email)
);

-- ---------------------------------------------------------------------
-- Histórico de sugestões — cada análise (imagem NÃO se guarda, só o
-- resultado estruturado que o Gemini devolveu + o prato indicado).
--
-- A linha nasce 'pendente' (resultado ainda null) assim que o pedido chega
-- à Edge Function, e é o browser lê o URL curto (analiseId) e passa a
-- sondar (polling) esta linha até 'concluido'/'erro' — a análise em si
-- corre à parte, em segundo plano (EdgeRuntime.waitUntil na função), e por
-- isso continua mesmo que o telemóvel bloqueie o ecrã ou o browser mude de
-- separador a meio: já não há um único pedido HTTP de 20-60s à espera de
-- resposta, que é o que morria sempre que o telemóvel suspendia a app.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wineselection.analises (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  user_email text NOT NULL DEFAULT '',   -- carimbado pelo trigger, nunca vem do cliente
  prato      text NOT NULL DEFAULT '',
  estado     text NOT NULL DEFAULT 'pendente',  -- 'pendente' | 'concluido' | 'erro'
  resultado  jsonb,                              -- só preenchido quando estado='concluido'
  erro       text,                               -- só preenchido quando estado='erro'
  -- Verificação "a sério" opcional, pedida à mão depois da análise: o
  -- utilizador escolhe até 5 vinhos de `resultado.vinhosCarta` (que só têm
  -- pontuacaoAprox de memória) e a Edge Function `verificar-vinhos` faz
  -- pesquisa Google real só para esses. Fica na MESMA linha porque pertence
  -- à mesma análise — null enquanto nunca foi pedida.
  verificacao_estado text,                        -- null | 'pendente' | 'concluido' | 'erro'
  verificacao         jsonb,                       -- [{nome,pontuacao,precoAvaliacao}], só quando concluido
  verificacao_erro    text,                        -- só quando erro
  criado_em  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT analises_pkey PRIMARY KEY (id),
  CONSTRAINT analises_estado_chk CHECK (estado IN ('pendente','concluido','erro')),
  CONSTRAINT analises_verificacao_estado_chk
    CHECK (verificacao_estado IS NULL OR verificacao_estado IN ('pendente','concluido','erro'))
);
CREATE INDEX IF NOT EXISTS analises_user_idx ON wineselection.analises (user_email, criado_em DESC);

-- ---------------------------------------------------------------------
-- Diagnóstico: cada chamada à Edge Function `sugerir-vinho` deixa uma linha
-- (a função grava com a service role — do lado do browser vê-se sempre
-- "502"/"504", a causa fica aqui). Mesmo padrão do goals.sync_log.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wineselection.sync_log (
  id        bigint GENERATED BY DEFAULT AS IDENTITY,
  acao      text NOT NULL DEFAULT 'sugerir_vinho',
  estado    text NOT NULL,               -- 'ok' | 'erro'
  quem      text,
  detalhe   jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sync_log_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS sync_log_criado_idx ON wineselection.sync_log (criado_em DESC);

-- ---------------------------------------------------------------------
-- GRANTs (sem isto: HTTP 403 / 42501 em tudo)
-- ---------------------------------------------------------------------
GRANT USAGE ON SCHEMA wineselection TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA wineselection TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA wineselection GRANT ALL ON TABLES TO anon, authenticated;

-- ---------------------------------------------------------------------
-- RLS (as policies ficam em policies.sql, depois de functions.sql)
-- ---------------------------------------------------------------------
ALTER TABLE wineselection.allowed_users   ENABLE ROW LEVEL SECURITY;
ALTER TABLE wineselection.access_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE wineselection.analises        ENABLE ROW LEVEL SECURITY;
ALTER TABLE wineselection.sync_log        ENABLE ROW LEVEL SECURITY;
